syc/views/menu_views.py
from flask import Blueprint, url_for, request,render_template,g, flash
from werkzeug.utils import redirect
from syc import db
from syc.forms import MenuCreateForm
from syc.models import User, Menu,Store
from .auth_views import login_required

bp = Blueprint('menu', __name__, url_prefix='/menu')



@bp.route('/create_menu/<int:store_id>/', methods=('GET', 'POST'))
@login_required
def create_menu(store_id):
    form = MenuCreateForm()
    store = Store.query.get_or_404(store_id)
    if request.method == 'POST' and form.validate_on_submit():
        menu = Menu.query.filter_by(menu_name=form.menu_name.data).first()
        if not menu:
            menu = Menu(
                        menu_name=form.menu_name.data,
                        price=form.price.data,
                        menu_content=form.menu_content.data,
                        user=g.user)
            store.menu_set.append(menu)
            db.session.commit()
            return redirect(url_for('store.detail', store_id=store_id))
    return render_template('my/create_menu.html',  form=form)

@bp.route('/modify/<int:menu_id>', methods=('GET', 'POST'))
@login_required
def modify(menu_id):
    menu = Menu.query.get_or_404(menu_id)
    if g.user != menu.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('store.detail', store_id=menu.store.id))
    if request.method == "POST":
        form = MenuCreateForm()
        if form.validate_on_submit():
            form.populate_obj(menu)
            db.session.commit()
            return redirect(url_for('store.detail', store_id=menu.store.id))
    else:
        form = MenuCreateForm(obj=menu)
    return render_template('my/create_menu.html', form=form)
@bp.route('/delete/<int:menu_id>')
@login_required
def delete(menu_id):
    menu = Menu.query.get_or_404(menu_id)
    store_id = menu.store.id
    if g.user != menu.user:
        flash('삭제권한이 없습니다')
    else:
        db.session.delete(menu)
        db.session.commit()
    return redirect(url_for('store.detail', store_id=store_id))


@bp.route('/inbag/<int:menu_id>/')
@login_required
def inbag(menu_id):

    _menu = Menu.query.get_or_404(menu_id)
    store_id=_menu.store.id
    if g.user == _menu.user:
        flash('본인가게 메뉴는 추가할 수 없습니다')
    else:
        g.user.money = int(g.user.money) + int(_menu.price)
        _menu.buyer.append(g.user)
        db.session.commit()

    return redirect(url_for('store.detail', store_id=store_id))

syc/views/my_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g

from werkzeug.utils import redirect

from syc import db
from syc.forms import StoreCreateForm
from syc.models import Store
from .auth_views import login_required

bp = Blueprint('my', __name__, url_prefix='/my')


@bp.route('/bag/', methods=('GET', 'POST'))
@login_required
def bag():
    return render_template('my/my.html')


@bp.route('/create_store/', methods=('GET', 'POST'))
@login_required
def create_store():
    form = StoreCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        store = Store.query.filter_by(store_name=form.store_name.data).first()
        if not store:
            store = Store(store_name=form.store_name.data,
                          store_type=request.form.get('store_type'),
                          s_phone=form.s_phone.data,
                          s_address=form.s_address.data,
                          store_intro=form.store_intro.data,
                          min_order=form.min_order.data,
                          deliver=form.deliver.data,
                          user=g.user )
            db.session.add(store)
            db.session.commit()
            return redirect(url_for('main.main'))
        else:
            flash('이미 존재하는 가게입니다.')
    return render_template('my/create_store.html', form=form)

@bp.route('/modify/<int:store_id>', methods=('GET', 'POST'))
@login_required
def modify(store_id):
    store = Store.query.get_or_404(store_id)
    if g.user != store.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('store.detail', store_id=store_id))
    if request.method == 'POST':  # POST 요청
        form = StoreCreateForm()
        if form.validate_on_submit():
            form.populate_obj(store)
            db.session.commit()
            return redirect(url_for('store.detail', store_id=store_id))
    else:  # GET 요청
        form = StoreCreateForm(obj=store)
    return render_template('my/create_store.html', form=form)

@bp.route('/delete/<int:store_id>')
@login_required
def delete(store_id):
    store = Store.query.get_or_404(store_id)
    if g.user != store.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('store.detail', store_id=store_id))
    db.session.delete(store)
    db.session.commit()
    return redirect(url_for('main.main'))

syc/views/store_view.py
from flask import Blueprint, url_for, render_template, flash, request, session, g

from werkzeug.utils import redirect

from syc import db
from syc.models import Store, Menu, User
from syc.views.auth_views import login_required

bp = Blueprint('store', __name__, url_prefix='/store')


@bp.route('/list/korean/')
def _list1():
    store_list = Store.query.filter(Store.store_type.like('한식')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/chinese/')
def _list2():
    store_list = Store.query.filter(Store.store_type.like('중식')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/japanese/')
def _list3():
    store_list = Store.query.filter(Store.store_type.like('일식')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/snack/')
def _list4():
    store_list = Store.query.filter(Store.store_type.like('분식')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/asian/')
def _list5():
    store_list = Store.query.filter(Store.store_type.like('아시안')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/chicken/')
def _list6():
    store_list = Store.query.filter(Store.store_type.like('치킨')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/pizza/')
def _list7():
    store_list = Store.query.filter(Store.store_type.like('피자')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/lunch/')
def _list8():
    store_list = Store.query.filter(Store.store_type.like('도시락')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/pork/')
def _list9():
    store_list = Store.query.filter(Store.store_type.like('족발')).all()
    return render_template('store/store_list.html', store_list=store_list)
@bp.route('/list/desert/')
def _list10():
    store_list = Store.query.filter(Store.store_type.like('디저트')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/fast/')
def _list11():
    store_list = Store.query.filter(Store.store_type.like('패스트푸드')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/dawn/')
def _list12():
    store_list = Store.query.filter(Store.store_type.like('야식')).all()
    return render_template('store/store_list.html', store_list=store_list)





@bp.route('/detail/<int:store_id>/')
def detail(store_id):
    store = Store.query.get_or_404(store_id)
    return render_template('store/store_detail.html', store=store)

@bp.route('/vote/<int:store_id>/')
@login_required
def vote(store_id):
    _store = Store.query.get_or_404(store_id)
    if g.user == _store.user:
        flash('본인가게는 찜 할 수 없습니다')
    else:
        _store.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('store.detail', store_id=store_id))

syc/templates/store/store_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="main-container">
    <!-- flash 오류 -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <!--가게-->
    <div class="store" style="cursor: pointer;">
        <label class="store-name">{{ store.store_name }}  </label>
        <a href="javascript:void(0)" data-uri="{{ url_for('store.vote', store_id=store.id) }}"
           class="recommend btn btn-sm"> 💖
            <span class="badge rounded-pill bg-success">{{ store.voter|length }}</span>
        </a>
        <br>
        <br>
        <label>최소주문 </label>
        <label class="store-deliver">{{ store.min_order }}</label>
        <label>원, 배달팁 </label>
        <label class="store-deliver">{{ store.deliver }}</label>
        <label>원</label>
        <br>
        <br>
        <label class="store-intro">{{ store.store_intro }}</label>
    </div>
    <div class="my-3">
        {% if g.user == store.user %}
        <div class="store-modify">
            <button type="button" method="post" class="modify" onclick="location.href='{{ url_for('my.modify', store_id=store.id) }}'; " >수정</button>
            <button type="button" method="post" class="delete" onclick="location.href='javascript:void(0)'; " data-uri="{{ url_for('my.delete', store_id=store.id) }}" >삭제</button>
        </div>
        {% endif %}
    </div>
    <br>
    <br>
    <!--메뉴-->
    {% for menu in store.menu_set %}
    <div class="menu-list">
        <div class="menu-label">
        <div>
        <label class="menu-name">{{ menu.menu_name }}</label>
        <label>, </label>

        <label class="menu-price">{{ menu.price }}</label>
        <label>원</label>
        <br>
        <br>
        </div>
        <div>
        <label class="menu-info">{{ menu.menu_content }}</label>
        </div>
            </div>
        {% if g.user == menu.user %}
        <div class="store-modify">
            <button type="button" method="post" class="modify" onclick="location.href='{{ url_for('menu.modify', menu_id=menu.id) }}'; " >수정</button>
            <button type="button" method="post" class="delete" onclick="location.href='javascript:void(0)'; " data-uri="{{ url_for('menu.delete', menu_id=menu.id) }}" >삭제</button>
        </div>
        {%else%}

        <button type="button" method="post" data-uri="{{ url_for('menu.inbag', menu_id=menu.id) }}"
                class="inbag btn btn-sm" onclick="location.href='javascript:void(0)', store_id=store.id) }}'; " >장바구니 추가</button>

        {% endif %}
    </div>
    {% endfor %}
    {% if g.user == store.user %}
    <br>
    <br>
    <div class="menu-create">
        <button type="button" method="post" class="menu-btn" onclick="location.href='{{ url_for('menu.create_menu', store_id=store.id) }}'; " >메뉴 생성</button>
    </div>
    {% endif %}
    <div><a class="bag" href="{{ url_for('my.bag') }}"><img src="https://ifh.cc/g/DtAA4w.png" width="80px" height="50%"/></a>
</div>
</div>

{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
                location.href = this.dataset.uri;
        };
    });
});

const inbag_elements = document.getElementsByClassName("inbag");
Array.from(inbag_elements).forEach(function(element) {
    element.addEventListener('click', function() {

        if(confirm("장바구니에 추가하시겠습니까?")) {
                location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

syc/templates/store/store_list.html
{% extends 'base.html' %}
{% block content %}
<div class="main-container">
    <table>
        {% if store_list %}
        {% for store in store_list %}
        <tr>
            <td>
                <div class="store" style="cursor: pointer;" onclick="location.href='{{ url_for('store.detail', store_id=store.id) }}';">
                    <label class="store-name">{{ store.store_name }}</label>
                    <br>
                    <br>
                    <label>최소주문 </label>
                    <label class="store-deliver">{{ store.min_order }}</label>
                    <label>원, 배달팁 </label>
                    <label class="store-deliver">{{ store.deliver }}</label>
                    <label>원</label>
                    <br>
                    <br>
                    <label class="store-intro">{{ store.store_intro }}</label>
                </div>
                <br>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>

            <td colspan="3"><h1>텅</h1></td>
        </tr>
        {% endif %}
    </table>

<div><a class="bag" href="{{ url_for('my.bag') }}"><img src="https://ifh.cc/g/DtAA4w.png" width="80px" height="50%"/></a></div>
</div>
{% endblock %}