syc/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from syc import db
from syc.forms import UserCreateForm, UserLoginForm
from syc.models import User
import functools



bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        is_store=request.form.get('is_store'),
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data,
                        phone=form.phone.data,
                        address=form.address.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.main'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)

@bp.route('/login/',methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            session['is_store'] = user.is_store
            _next = request.args.get('next', '')
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for('main.main'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.before_app_request
def load_logged_in_store():
    is_store = session.get('is_store')
    user_id = session.get('user_id')
    if is_store ==0:
        g.store = User.query.get(user_id)

    else:
        g.store = None

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.main'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.login', next=_next))
        return view(*args, **kwargs)
    return wrapped_view

@bp.route('/modify/<int:user_id>', methods=('GET', 'POST'))
@login_required
def modify(user_id):
    user = User.query.get_or_404(user_id)
    if request.method == 'POST':  # POST 요청
        form = UserCreateForm()
        if form.validate_on_submit():
            form.populate_obj(user)
            db.session.commit()
            return redirect(url_for('main.main', user_id=user_id))
    else:  # GET 요청
        form = UserCreateForm(obj=user)
    return render_template('auth/signup.html', form=form)

syc/views/main_views.py
from flask import Blueprint, url_for, render_template, flash, request, session
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from syc import db
from syc.forms import UserCreateForm, UserLoginForm
from syc.models import User

bp=Blueprint('main',__name__,url_prefix='/')

@bp.route('/')
def main():
    return render_template('main.html')

syc/views/my_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g

from werkzeug.utils import redirect

from syc import db
from syc.forms import StoreCreateForm
from syc.models import Store
from .auth_views import login_required

bp = Blueprint('my', __name__, url_prefix='/my')


@bp.route('/bag/', methods=('GET', 'POST'))
@login_required
def bag():
    return render_template('my/my.html')


@bp.route('/create_store/', methods=('GET', 'POST'))
@login_required
def create_store():
    form = StoreCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        store = Store.query.filter_by(store_name=form.store_name.data).first()
        if not store:
            store = Store(store_name=form.store_name.data,
                          store_type=request.form.get('store_type'),
                          s_phone=form.s_phone.data,
                          s_address=form.s_address.data,
                          store_intro=form.store_intro.data,
                          min_order=form.min_order.data,
                          deliver=form.deliver.data,
                          user=g.user )
            db.session.add(store)
            db.session.commit()
            return redirect(url_for('main.main'))
        else:
            flash('이미 존재하는 가게입니다.')
    return render_template('my/create_store.html', form=form)

@bp.route('/modify/<int:store_id>', methods=('GET', 'POST'))
@login_required
def modify(store_id):
    store = Store.query.get_or_404(store_id)
    if g.user != store.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('store.detail', store_id=store_id))
    if request.method == 'POST':  # POST 요청
        form = StoreCreateForm()
        if form.validate_on_submit():
            form.populate_obj(store)
            db.session.commit()
            return redirect(url_for('store.detail', store_id=store_id))
    else:  # GET 요청
        form = StoreCreateForm(obj=store)
    return render_template('my/create_store.html', form=form)

@bp.route('/delete/<int:store_id>')
@login_required
def delete(store_id):
    store = Store.query.get_or_404(store_id)
    if g.user != store.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('store.detail', store_id=store_id))
    db.session.delete(store)
    db.session.commit()
    return redirect(url_for('main.main'))

syc/views/store_view.py
from flask import Blueprint, url_for, render_template, flash, request, session, g

from werkzeug.utils import redirect

from syc import db
from syc.models import Store, Menu, User
from syc.views.auth_views import login_required

bp = Blueprint('store', __name__, url_prefix='/store')


@bp.route('/list/korean/')
def _list1():
    store_list = Store.query.filter(Store.store_type.like('한식')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/chinese/')
def _list2():
    store_list = Store.query.filter(Store.store_type.like('중식')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/japanese/')
def _list3():
    store_list = Store.query.filter(Store.store_type.like('일식')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/snack/')
def _list4():
    store_list = Store.query.filter(Store.store_type.like('분식')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/asian/')
def _list5():
    store_list = Store.query.filter(Store.store_type.like('아시안')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/chicken/')
def _list6():
    store_list = Store.query.filter(Store.store_type.like('치킨')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/pizza/')
def _list7():
    store_list = Store.query.filter(Store.store_type.like('피자')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/lunch/')
def _list8():
    store_list = Store.query.filter(Store.store_type.like('도시락')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/pork/')
def _list9():
    store_list = Store.query.filter(Store.store_type.like('족발')).all()
    return render_template('store/store_list.html', store_list=store_list)
@bp.route('/list/desert/')
def _list10():
    store_list = Store.query.filter(Store.store_type.like('디저트')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/fast/')
def _list11():
    store_list = Store.query.filter(Store.store_type.like('패스트푸드')).all()
    return render_template('store/store_list.html', store_list=store_list)

@bp.route('/list/dawn/')
def _list12():
    store_list = Store.query.filter(Store.store_type.like('야식')).all()
    return render_template('store/store_list.html', store_list=store_list)





@bp.route('/detail/<int:store_id>/')
def detail(store_id):
    store = Store.query.get_or_404(store_id)
    return render_template('store/store_detail.html', store=store)

@bp.route('/vote/<int:store_id>/')
@login_required
def vote(store_id):
    _store = Store.query.get_or_404(store_id)
    if g.user == _store.user:
        flash('본인가게는 찜 할 수 없습니다')
    else:
        _store.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('store.detail', store_id=store_id))

syc/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <!-- pybo CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>배달의 민족</title>
    <link href="https://fonts/googleapis.com/earlyaccess/notosanskr.css" rel="stylesheet">
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
<!-- Bootstrap JS -->
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

syc/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

syc/templates/main.html
{% extends "base.html" %}
{% block content %}
<div class="main-container">

    <table>
        <tr>
            <td> <div class="menu" style=" cursor: pointer;" onclick="location.href='{{ url_for('store._list1') }}';">
                <label class="menu-name">한식</label>
                <br>
                <label class="menu-name2">Korean Food</label>
                <br>
                <img src="https://ifh.cc/g/n7QjYJ.png"/>
            </div></td>
            <td> <div class="menu" style=" cursor: pointer;" onclick="location.href='{{ url_for('store._list2') }}';">
                <label class="menu-name">중식</label>
                <br>
                <label class="menu-name2">Chinese Food</label>
                <br>
                <img src="https://ifh.cc/g/2KkMB5.png"/>
            </div></td>
            <td> <div class="menu" style=" cursor: pointer;" onclick="location.href='{{ url_for('store._list3') }}';">
                <label class="menu-name">일식</label>
                <br>
                <label class="menu-name2">Japanese Food</label>
                <br>
                <img src="https://ifh.cc/g/LNgNBk.png"/>
            </div></td>
            <td> <div class="menu" style=" cursor: pointer;" onclick="location.href='{{ url_for('store._list4') }}';">
                <label class="menu-name">분식</label>
                <br>
                <label class="menu-name2">Snack Menu</label>
                <br>
                <img src="https://ifh.cc/g/Oaaoy0.png"/>
            </div></td>
        </tr>
        <tr>
            <td> <div class="menu" style=" cursor: pointer;" onclick="location.href='{{ url_for('store._list5') }}';">
                <label class="menu-name">아시안</label>
                <br>
                <label class="menu-name2">Asian Food</label>
                <br>
                <img src="https://ifh.cc/g/MWXjOG.png"/>
            </div></td>
            <td> <div class="menu" style=" cursor: pointer;" onclick="location.href='{{ url_for('store._list6') }}';">
                <label class="menu-name">치킨</label>
                <br>
                <label class="menu-name2">Chicken</label>
                <br>
                <img src="https://ifh.cc/g/nFda4Y.png"/>
            </div></td>
            <td> <div class="menu" style=" cursor: pointer;" onclick="location.href='{{ url_for('store._list7') }}';">
                <label class="menu-name">피자</label>
                <br>
                <label class="menu-name2">Pizza</label>
                <br>
                <img src="https://ifh.cc/g/BHBSVC.png"/>
            </div></td>
            <td> <div class="menu" style=" cursor: pointer;" onclick="location.href='{{ url_for('store._list8') }}';">
                <label class="menu-name">도시락</label>
                <br>
                <label class="menu-name2">Lunch Box</label>
                <br>
                <img src="https://ifh.cc/g/lchJao.png"/>
            </div></td>
        </tr>
        <tr>
            <td> <div class="menu" style=" cursor: pointer;" onclick="location.href='{{ url_for('store._list9') }}';">
                <label class="menu-name">족발</label>
                <br>
                <label class="menu-name2">Pork Feet</label>
                <br>
                <img src="https://ifh.cc/g/8gMB36.png"/>
            </div></td>
            <td> <div class="menu" style=" cursor: pointer;" onclick="location.href='{{ url_for('store._list10') }}';">
                <label class="menu-name">디저트</label>
                <br>
                <label class="menu-name2">Desert</label>
                <br>
                <img src="https://ifh.cc/g/A7faQ6.png"/>
            </div></td>
            <td> <div class="menu" style=" cursor: pointer;" onclick="location.href='{{ url_for('store._list11') }}';">
                <label class="menu-name">패스트푸드</label>
                <br>
                <label class="menu-name2">Fast Food</label>
                <br>
                <img src="https://ifh.cc/g/ht68fh.png"/>
            </div></td>
            <td> <div class="menu" style=" cursor: pointer;" onclick="location.href='{{ url_for('store._list12') }}';">
                <label class="menu-name">야식</label>
                <br>
                <label class="menu-name2">Dawn Food</label>
                <br>
                <img src="https://ifh.cc/g/oWWW4V.png"/>
            </div></td>
        </tr>

    </table>
    {% if g.store %}
        <div class="store-create">
            <button type="button" class="store-btn" onclick="location.href='{{ url_for('my.create_store') }}' ">가게 생성</button>
        </div>
    {% endif %}

</div>

{% endblock %}

syc/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.main') }}"><img src="https://ifh.cc/g/21vfnM.png" width="130px" height="30%"/></a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if g.user %}
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
                </li>
            </ul>
            <div class="location">
                <label class="address" style="float:center;">{{ g.user.address }}</label>
            </div>
            <div class="my" style="float:right;">

                <a class="nav-link" method="post" href="{{ url_for('auth.modify', user_id=g.user.id) }}"><img src="https://ifh.cc/g/HnK8Ga.png" width="25px" height="30%"/></a>
            </div>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                </li>

            </ul>
            {% endif %}
        </div>

        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


    </div>

</nav>